#!/usr/bin/env bash
# Builds the WebAssembly Micro Runtime as a static library for iOS device arm64
# and iOS simulator arm64, fast interpreter only (no AOT, no JIT: iOS apps
# cannot map executable memory), with WASI preview 1, and packages it as
# Toolchain/build/xcframeworks/LemonSeedWAMR.xcframework.
#
# Usage: build-wamr-ios.sh [macos]   ("macos" also builds a host slice for tests)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLCHAIN_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=../versions.env
source "$TOOLCHAIN_DIR/versions.env"

BUILD_DIR="$TOOLCHAIN_DIR/build"
DOWNLOADS="$BUILD_DIR/downloads"
SRC="$BUILD_DIR/src/wasm-micro-runtime-WAMR-$WAMR_VERSION"
OUT_DIR="$BUILD_DIR/xcframeworks"
JOBS="${JOBS:-10}"

mkdir -p "$DOWNLOADS" "$OUT_DIR" "$BUILD_DIR/src"

tarball="$DOWNLOADS/wamr-WAMR-$WAMR_VERSION.tar.gz"
if [[ ! -f "$tarball" ]]; then
  curl -fL --retry 3 -o "$tarball.part" "$WAMR_URL"
  mv "$tarball.part" "$tarball"
fi
echo "$WAMR_SHA256  $tarball" | shasum -a 256 -c -
[[ -d "$SRC" ]] || tar -xzf "$tarball" -C "$BUILD_DIR/src"

# WAMR feature set shared by every slice.
WAMR_FLAGS=(
  -DWAMR_BUILD_PLATFORM=darwin
  -DWAMR_BUILD_TARGET=AARCH64
  -DWAMR_BUILD_INTERP=1
  -DWAMR_BUILD_FAST_INTERP=1
  -DWAMR_BUILD_AOT=0
  -DWAMR_BUILD_JIT=0
  -DWAMR_BUILD_FAST_JIT=0
  -DWAMR_BUILD_LIBC_WASI=1
  -DWAMR_BUILD_LIBC_BUILTIN=0
  -DWAMR_BUILD_MULTI_MODULE=0
  -DWAMR_BUILD_LIB_PTHREAD=0
  -DWAMR_BUILD_LIB_WASI_THREADS=0
  -DWAMR_BUILD_SIMD=0
  -DWAMR_BUILD_REF_TYPES=1
  -DWAMR_BUILD_BULK_MEMORY=1
  -DWAMR_BUILD_DUMP_CALL_STACK=1
  -DWAMR_BUILD_MEMORY_PROFILING=0
  -DWAMR_BUILD_INSTRUCTION_METERING=0
  # Software bounds checks: the hardware scheme reserves 8 GB of address space
  # per instance and installs a SIGSEGV handler in the host app, neither of
  # which is acceptable inside the IDE process on iPadOS.
  -DWAMR_DISABLE_HW_BOUND_CHECK=1
)

build_slice() { # name sdk extra-cmake-args...
  local name="$1" sdk="$2"; shift 2
  local bdir="$BUILD_DIR/wamr-$name"
  rm -rf "$bdir"
  cmake -G Ninja -S "$SRC" -B "$bdir" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_OSX_SYSROOT="$(xcrun --sdk "$sdk" --show-sdk-path)" \
    -DCMAKE_OSX_ARCHITECTURES=arm64 \
    -DBUILD_SHARED_LIBS=OFF \
    "${WAMR_FLAGS[@]}" "$@"
  ninja -C "$bdir" -j "$JOBS" vmlib
}

build_slice ios-device iphoneos \
  -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET"
build_slice ios-sim iphonesimulator \
  -DCMAKE_SYSTEM_NAME=iOS -DCMAKE_OSX_DEPLOYMENT_TARGET="$IOS_DEPLOYMENT_TARGET"
if [[ "${1:-}" == macos ]]; then
  build_slice macos macosx -DCMAKE_OSX_DEPLOYMENT_TARGET=26.0
fi

# Public headers (namespaced under wamr/ so they cannot collide with other
# libraries' headers in the app's include directory).
headers="$BUILD_DIR/wamr-headers"
rm -rf "$headers"
mkdir -p "$headers/wamr"
cp "$SRC"/core/iwasm/include/{wasm_export.h,lib_export.h,wasm_c_api.h} "$headers/wamr/"
mkdir -p "$headers/lemonseed"
printf '/* Generated by build-wamr-ios.sh */\n#define LST_HAVE_WAMR 1\n' >"$headers/lemonseed/wamr_config.h"

args=()
for name in ios-device ios-sim macos; do
  lib="$BUILD_DIR/wamr-$name/libiwasm.a"
  [[ -f "$lib" ]] && args+=(-library "$lib" -headers "$headers")
done
rm -rf "$OUT_DIR/LemonSeedWAMR.xcframework"
xcodebuild -create-xcframework "${args[@]}" -output "$OUT_DIR/LemonSeedWAMR.xcframework"
du -sh "$BUILD_DIR"/wamr-*/libiwasm.a
