import CryptoKit
import Foundation
import Testing
@testable import GitKit

@Suite struct SSHKeyTests {
    @Test func ed25519PublicKeyFormat() throws {
        let key = Ed25519SSHKey()
        let line = key.openSSHPublicKey(comment: "ipad")
        #expect(line.hasPrefix("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAI"))
        #expect(line.hasSuffix(" ipad"))
        let parsed = try SSHPublicKey.parse(line)
        #expect(parsed.algorithm == "ssh-ed25519")
        #expect(parsed.blob == key.publicKeyBlob)
        #expect(key.fingerprint.hasPrefix("SHA256:"))
        #expect(key.fingerprint.count == 7 + 43)
    }

    @Test func ed25519SignatureBodyVerifies() throws {
        let key = Ed25519SSHKey()
        let data = Data("session data".utf8)
        let body = try key.signatureBody(for: data)
        #expect(body.count == 64)
        #expect(key.privateKey.publicKey.isValidSignature(body, for: data))
    }

    @Test func p256SignatureBodyIsTwoMpints() throws {
        let key = P256SSHKey()
        #expect(key.openSSHPublicKey().hasPrefix("ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABB"))
        let data = Data("session data".utf8)
        var reader = SSHWire.Reader(try key.signatureBody(for: data))
        let r = try reader.string()
        let s = try reader.string()
        #expect(reader.isAtEnd)
        func fixed(_ d: Data) -> Data {
            var d = Data(d.drop { $0 == 0 })
            while d.count < 32 { d.insert(0, at: 0) }
            return d
        }
        let sig = try P256.Signing.ECDSASignature(rawRepresentation: fixed(r) + fixed(s))
        #expect(key.privateKey.publicKey.isValidSignature(sig, for: data))
    }

    @Test func mpintEncoding() {
        #expect(SSHWire.mpint(Data([0x00, 0x7f])) == Data([0, 0, 0, 1, 0x7f]))
        #expect(SSHWire.mpint(Data([0x80])) == Data([0, 0, 0, 2, 0, 0x80]))
    }

    @Test(arguments: [SSHKeyKind.ed25519, .p256])
    func sshsigRoundTrip(kind: SSHKeyKind) throws {
        let key: any SSHSigningKey = kind == .ed25519 ? Ed25519SSHKey() : P256SSHKey()
        let message = Data("tree abc\nauthor A <a@b> 1 +0000\n\nmsg\n".utf8)
        let armored = try SSHSignature.sign(message, key: key)
        #expect(armored.hasPrefix("-----BEGIN SSH SIGNATURE-----\n"))
        #expect(armored.hasSuffix("-----END SSH SIGNATURE-----"))
        #expect(try SSHSignature.verify(armored, message: message))
        #expect(try !SSHSignature.verify(armored, message: message + Data("x".utf8)))
        #expect(try !SSHSignature.verify(armored, message: message, namespace: "file"))
    }

    @Test func openSSHPrivateKeyRoundTrip() async throws {
        let store = SSHKeyStore(store: InMemorySecretStore())
        let info = try await store.generate(.ed25519, label: "laptop")
        let pem = try await store.exportOpenSSHPrivateKey(info.id)
        #expect(pem.hasPrefix("-----BEGIN OPENSSH PRIVATE KEY-----"))
        let other = SSHKeyStore(store: InMemorySecretStore())
        let imported = try await other.importOpenSSHPrivateKey(pem)
        #expect(imported.publicKeyBlob == info.publicKeyBlob)
        #expect(imported.label == "laptop")

        let p256 = try await store.generate(.p256, label: "ecdsa")
        let p256pem = try await store.exportOpenSSHPrivateKey(p256.id)
        #expect(try await other.importOpenSSHPrivateKey(p256pem).publicKeyBlob == p256.publicKeyBlob)
    }

    /// A throwaway key generated by `ssh-keygen -t ed25519 -N '' -C test` parses.
    @Test func importsKeyFromSSHKeygen() async throws {
        let pem = """
        -----BEGIN OPENSSH PRIVATE KEY-----
        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
        QyNTUxOQAAACDEWgKLy/x5EY60ckbEsq7/lkd30pVhzLrPVDdJcmtIaQAAAIiAw8FTgMPB
        UwAAAAtzc2gtZWQyNTUxOQAAACDEWgKLy/x5EY60ckbEsq7/lkd30pVhzLrPVDdJcmtIaQ
        AAAEDfVs1HcLfpwworahC/gSOSzmpLDpKV5xwMj3pHxpkxBcRaAovL/HkRjrRyRsSyrv+W
        R3fSlWHMus9UN0lya0hpAAAABHRlc3QB
        -----END OPENSSH PRIVATE KEY-----
        """
        let store = SSHKeyStore(store: InMemorySecretStore())
        let info = try await store.importOpenSSHPrivateKey(pem)
        #expect(info.label == "test")
        #expect(info.openSSHPublicKey == "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMRaAovL/HkRjrRyRsSyrv+WR3fSlWHMus9UN0lya0hp test")
    }

    @Test func keyStoreLifecycle() async throws {
        let store = SSHKeyStore(store: InMemorySecretStore())
        let a = try await store.generate(.ed25519, label: "a")
        let b = try await store.generate(.p256, label: "b")
        #expect(try await store.keys().map(\.id) == [a.id, b.id])
        let signer = try await store.signingKey(for: a.id)
        #expect(signer.publicKeyBlob == a.publicKeyBlob)
        try await store.rename(b.id, to: "renamed")
        #expect(try await store.keys().last?.label == "renamed")
        try await store.delete(a.id)
        #expect(try await store.keys().map(\.id) == [b.id])
        if SecureEnclaveSSHKey.isAvailable {
            let se = try await store.generate(.secureEnclave, label: "se")
            #expect(se.algorithm == "ecdsa-sha2-nistp256")
            await #expect(throws: SSHKeyError.self) { try await store.exportOpenSSHPrivateKey(se.id) }
        } else {
            await #expect(throws: SSHKeyError.secureEnclaveUnavailable) { try await store.generate(.secureEnclave, label: "se") }
        }
    }

    @Test func keychainStoreWhenAvailable() throws {
        guard KeychainSecretStore.isAvailable else { return }
        let store = KeychainSecretStore()
        let service = "studio.git.tests.\(UUID().uuidString)"
        try store.write(Data("one".utf8), service: service, account: "a")
        try store.write(Data("two".utf8), service: service, account: "a")
        #expect(try store.read(service: service, account: "a") == Data("two".utf8))
        #expect(try store.accounts(service: service) == ["a"])
        try store.delete(service: service, account: "a")
        #expect(try store.read(service: service, account: "a") == nil)
    }

    @Test func signedCommitCarriesVerifiableSSHSignature() async throws {
        let (dir, repo) = try await makeRepo()
        let key = Ed25519SSHKey()
        try dir.write("signed.txt", "signed\n")
        try await repo.stageAll()
        let id = try await repo.commit(message: "Signed commit", options: CommitOptions(signer: SSHCommitSigner(key: key)))
        let info = try await repo.commitInfo(id)
        #expect(info.isSigned)
        // Split the raw object into signature and signed payload like Git does.
        let (signature, payload) = try await repo.commitSignature(id)
        #expect(try SSHSignature.verify(signature, message: payload))
    }

    @Test func knownHostsDecisions() async {
        let store = KnownHostsStore(file: nil)
        let github = try! SSHPublicKey.parse("ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl")
        #expect(store.decision(host: "github.com", keyType: "ssh-ed25519", key: github.blob) == .trusted)
        let other = Ed25519SSHKey().publicKeyBlob
        #expect(store.decision(host: "github.com", keyType: "ssh-ed25519", key: other) == .mismatch)
        #expect(await store.trustSSHHost("github.com", keyType: "ssh-ed25519", fingerprint: "", hostKey: other) == false)
        #expect(await store.trustSSHHost("git.example.com", keyType: "ssh-ed25519", fingerprint: "", hostKey: other) == false)
        store.confirmNewHost = { _, _, _ in true }
        #expect(await store.trustSSHHost("git.example.com", keyType: "ssh-ed25519", fingerprint: "", hostKey: other) == true)
        #expect(store.decision(host: "git.example.com", keyType: "ssh-ed25519", key: other) == .trusted)
    }
}
